apiVersion: v1
data:
  filebeat.yml: |-
    filebeat.inputs:
    - type: log
      paths:
        - /var/log/postgresql/*.log
      processors:
      - add_kubernetes_metadata:
          in_cluster: true
    output.elasticsearch:
      hosts: '${ELASTICSEARCH_HOSTS:elasticsearch-master:9200}'
kind: ConfigMap
metadata:
  labels:
    app: elk-filebeat
  name: filebeat-config
  namespace: elastic-stack

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: filebeat-service-account

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  # "namespace" omitted since ClusterRoles are not namespaced
  name: filebeat-cluster-role
rules:
- apiGroups: [""]
  resources: ["namespaces","pods"]
  verbs: ["get", "watch", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: filebeat-cluster-role-binding
subjects:
- kind: ServiceAccount
  name: filebeat-service-account # Name is case sensitive
  namespace: elastic-stack
roleRef:
  kind: ClusterRole
  name: filebeat-cluster-role
  apiGroup: "rbac.authorization.k8s.io"