apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: filebeat-cluster-role-binding
subjects:
- kind: ServiceAccount
  name: filebeat-service-account # Name is case sensitive
  namespace: elastic-stack
roleRef:
  kind: ClusterRole
  name: filebeat-cluster-role
  apiGroup: "rbac.authorization.k8s.io"