apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: elk-stack
spec:
  replicas: 1
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-postgres-filebeat
  template:
    metadata:
      labels:
          workload.user.cattle.io/workloadselector: deployment-postgres-filebeat
    spec:
      containers:
      - env:
        - name: POSTGRES_PASSWORD
          value: postgres
        image: proventa/postgres
        imagePullPolicy: Always
        name: postgres
        ports:
        - containerPort: 5432
          name: postgres-port
          protocol: TCP
        resources:
          limits:
            cpu: "1"
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 100Mi
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        volumeMounts:
        - mountPath: /var/log/postgresql
          name: pg-log
      - env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        image: docker.elastic.co/beats/filebeat:7.6.2
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - '#!/usr/bin/env bash -ecurl --fail 127.0.0.1:5066'
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        name: filebeat-logshipper
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - '#!/usr/bin/env bash -efilebeat test output'
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        resources:
          limits:
            cpu: "1"
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 100Mi
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
          readOnlyRootFilesystem: false
          runAsUser: 0
        volumeMounts:
        - mountPath: /var/log/postgresql
          name: pg-log
          readOnly: true
        - mountPath: /usr/share/filebeat/filebeat.yml
          name: filebeat-config
          readOnly: true
          subPath: filebeat.yml
      restartPolicy: Always
      serviceAccountName: filebeat-service-account
      terminationGracePeriodSeconds: 30
      volumes:
      - name: pg-log
        persistentVolumeClaim:
          claimName: pg-log
      - configMap:
          defaultMode: 384
          name: filebeat-config
          optional: false
        name: filebeat-config